### ISSUE TITLE
Cannot download the 3D models

### ISSUE THREAD

**Issue by MyNiuuu** [ShuhongChen/vroid-dataset#1]
Thank you for the great work!

But I have some problems downloading the 3D models. Specifically, I configure the docker and run the corresponding commands, and scrapy gives me these responces:

```
$ sudo bash ./run.sh
Creating network "vroid-dataset_default" with the default driver
Creating scrapy ... done
Attaching to scrapy
scrapy    | 
scrapy    | 
scrapy    | ==========  Initializing Spider ==========
scrapy    | Loading Model List From File: _data/lustrous/raw/vroid/metadata.json
scrapy    | Loaded 16029 Models From File
scrapy    | Max Model Count:  20000
scrapy    | Max Duplicate Models Found:  50
scrapy    | Spider Initialized................
scrapy    | 
scrapy    | 
scrapy    | 
scrapy    | 
scrapy    | 
scrapy    | ========== Finished Crawling ==========
scrapy    | 
scrapy    | 
scrapy    | Models Collected: 
scrapy    | 16029
scrapy exited with code 0
Removing scrapy ... done
Removing network vroid-dataset_default
```

However, I cannot find any downloaded 3d model in the current directory, and only find two new folders:
1. `data` folder which contains a json file datmodels.json
2. `files` folder which is empty

And it seems that I also have no additional files except for the `metadata.json` in `./_data/lustrous/raw/vroid`.

**Comment by ShuhongChen** [comment]
This is sort of weird; I just ran `sudo bash ./run.sh` again on my machine and it works...

My best guess right now is either:
1) you're somehow running with `mode!="d"`, which only collects the metadata without downloading models, so scrapy thinks it's done; `MODE=d` by default in `run.sh:3`, but you can double-check by `print(self.mode)` in `./VRoidSpider/VRoidSpider/spiders/VroidSpider.py:55`
2) maybe there's an authentication error with the cookie?  you can check `self.cookie` at `./VRoidSpider/VRoidSpider/spiders/VroidSpider.py:52` should be the one you got from logging into vroid website

How long did you let this run for, and is there output between `Initialized...` and `Finished`?

**Comment by MyNiuuu** [comment]
Thanks for your quick reply!

> you can double-check by print(self.mode) in ./VRoidSpider/VRoidSpider/spiders/VroidSpider.py:55

I print the `self.mode`, and it comes that the mode was indeed 'd'.

> you can check self.cookie at ./VRoidSpider/VRoidSpider/spiders/VroidSpider.py:52 should be the one you got from logging into vroid website

I print `cookie` at `./VRoidSpider/VRoidSpider/spiders/VroidSpider.py:52`, and it prints '1234567890cookie', is it correct?

> How long did you let this run for, and is there output between Initialized... and Finished?

The script runs about 3 minutes after I ran `sudo bash ./run.sh`. It stucks after printing `Attaching to scrapy` for 3 minutes, and takes only about one second to print the rest contents. There are no other output between `Spider Initialized................` and `========== Finished Crawling ==========`.

**Comment by ShuhongChen** [comment]
> 1234567890cookie

Oh, this is the problem; you need to go to vroid hub and get the right cookie (see instructions in [`./_env/vroid_cookie.bashrc`](https://github.com/ShuhongChen/vroid-dataset/blob/a0f7af944a2e0374aee885a4416129014869ebc0/_env/vroid_cookie_template.bashrc#L5))

Sorry if the instructions weren't clear; I added these instructions to the readme directly now
