### ISSUE TITLE
请问metadata.json是怎么生成的呀

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [ShuhongChen/vroid-dataset#4]
如题，想要增加更多需要爬的数据

**Comment by ShuhongChen** [comment]
你好，这里的metadata是scraper自己生成的；如果希望从新生成的话把`MODE`从`d`改成`c`因该就可以了：
https://github.com/ShuhongChen/vroid-dataset/blob/88af3c97f7407b792e49cacd17634983362684ce/run.sh#L3C4-L3C4

解释：
https://github.com/ShuhongChen/vroid-dataset/blob/88af3c97f7407b792e49cacd17634983362684ce/VRoidSpider/VRoidSpider/spiders/VRoidSpider.py#L47C9-L47C9

**Comment by abc2cba** [comment]
@ShuhongChen 
Referring the paper
> The 11.2k renders we use represent 70% retension of our original 16.0k scraped models.

It seems the provided metadata contains the origin 16k models. Could you provide the 11.2k version?

**Comment by ShuhongChen** [comment]
Hello, yes the metadata file contains the full 16k+ models, the 11k subset is in the drive download file:
https://github.com/ShuhongChen/vroid-dataset?tab=readme-ov-file#download
`panic_data_models_merged/_data/lustrous/subsets/rutileEB_all.csv`

**Comment by abc2cba** [comment]
> Hello, yes the metadata file contains the full 16k+ models, the 11k subset is in the drive download file: https://github.com/ShuhongChen/vroid-dataset?tab=readme-ov-file#download `panic_data_models_merged/_data/lustrous/subsets/rutileEB_all.csv`

Thanks! 
Are these models filtered by code solely or with human-audit afterward? 
I found some models are not human-shape but with bones attached. 
![8319657541852525547_Swinging_171](https://github.com/ShuhongChen/vroid-dataset/assets/141840759/9fd6364c-b104-48fc-9194-8fc9f75a4cb1)

**Comment by ShuhongChen** [comment]
Yes, there are a lot of non-human/joke models unfortunately; we used some heuristics to filter the dataset, but I can't guarantee finding the original script

From what I remember, I think we rendered them from the front, and filtered based on percent of alpha channel covered, and clip similarity to an anime text description
