### ISSUE TITLE
Dataset downloading problem

### ISSUE THREAD

**Issue by Boyyeo** [ShuhongChen/vroid-dataset#6]
Thanks for this great works ! 
 I wonder that if there is other way for downloading the multi-view images vroid 3d dataset ,
without using the docker container? maybe  somethings like Google Drive or somethings other...
Thanks again!

**Comment by ShuhongChen** [comment]
Hi, thanks for your interest in our work; unfortunately we're not allowed to directly host the rendered images, I'm afraid re-rendering is the only option at the moment
