### ISSUE TITLE
how to work on windows system?

### ISSUE THREAD

**Issue by TheBruin01** [ShuhongChen/vroid-dataset#8]
i finished docker-compose build and i turn run.sh to 1.bat. but it didn't work

"""
set MODE=d
set MAX_MODELS=20000
set JSON_FILE=D:\x\vroid-dataset-master\_data\lustrous\raw\vroid\metadata.json
set COOKIE=600xxxxxxxxxx53

docker-compose up

docker-compose down
"""

time="2024-07-19T16:14:13+08:00" level=warning msg="D:\\x\\vroid-dataset-master\\vroid-dataset-master\\docker-compose.yml: `version` is obsolete"
[+] Running 2/2
 ✔ Network vroid-dataset-master_default  Created                                                                                                                                        0.0s 
 ✔ Container scrapy                      Created                                                                                                                                        0.1s 
Attaching to scrapy
scrapy  | 
scrapy  |
scrapy  | ==========  Initializing Spider ==========
scrapy  | Loading Model List From File: D:\x\vroid-dataset-master\_data\lustrous\raw\vroid\metadata.json
scrapy  | Unhandled error in Deferred:
scrapy  | 2024-07-19 08:14:13 [twisted] CRITICAL: Unhandled error in Deferred:
scrapy  |
scrapy  | Traceback (most recent call last):
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 192, in crawl
scrapy  |     return self._crawl(crawler, *args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 196, in _crawl
scrapy  |     d = crawler.crawl(*args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1909, in unwindGenerator
scrapy  |     return _cancellableInlineCallbacks(gen)  # type: ignore[unreachable]
scrapy  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
scrapy  |     _inlineCallbacks(None, gen, status)
scrapy  | --- <exception caught here> ---
scrapy  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
scrapy  |     result = current_context.run(gen.send, result)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 86, in crawl
scrapy  |     self.spider = self._create_spider(*args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 98, in _create_spider
scrapy  |     return self.spidercls.from_crawler(self, *args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
scrapy  |     spider = cls(*args, **kwargs)
scrapy  |   File "/app/VRoidSpider/spiders/VRoidSpider.py", line 69, in __init__
scrapy  |     with open(json_file) as in_file:
scrapy  | builtins.FileNotFoundError: [Errno 2] No such file or directory: 'D:\\x\\vroid-dataset-master\\_data\\lustrous\\raw\\vroid\\metadata.json'
scrapy  |
scrapy  | 2024-07-19 08:14:13 [twisted] CRITICAL:
scrapy  | Traceback (most recent call last):
scrapy  |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
scrapy  |     result = current_context.run(gen.send, result)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 86, in crawl
scrapy  |     self.spider = self._create_spider(*args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/crawler.py", line 98, in _create_spider
scrapy  |     return self.spidercls.from_crawler(self, *args, **kwargs)
scrapy  |   File "/usr/local/lib/python3.9/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
scrapy  |     spider = cls(*args, **kwargs)
scrapy  |   File "/app/VRoidSpider/spiders/VRoidSpider.py", line 69, in __init__
scrapy  |     with open(json_file) as in_file:
scrapy  | FileNotFoundError: [Errno 2] No such file or directory: 'D:\\x\\vroid-dataset-master\\_data\\lustrous\\raw\\vroid\\metadata.json'
scrapy exited with code 1

D:\x\vroid-dataset-master>docker-compose down
time="2024-07-19T16:14:14+08:00" level=warning msg="D:\\x\\vroid-dataset-master\\docker-compose.yml: `version` is obsolete"
[+] Running 2/2
 ✔ Container scrapy                      Removed                                                                                                                                        0.0s 
 ✔ Network vroid-dataset-master_default  Removed

**Comment by ShuhongChen** [comment]
As the error says, you're missing the metadata file
https://github.com/ShuhongChen/vroid-dataset?tab=readme-ov-file#download

The codebase hasn't been tested on windows, if you run into issues down the line I'd recommend WSL if you don't have a linux machine
