### ISSUE TITLE
i can use for download vrm models?

### ISSUE THREAD

**Issue by Be3up** [ShuhongChen/vroid-dataset#9]
![изображение_2024-09-17_161519519](https://github.com/user-attachments/assets/90f5f50f-2555-40f8-92c6-46321c55e69e)
can i use this repository to download a model from vroid hub, unfortunately i cant download some directly via the button?

**Comment by ShuhongChen** [comment]
Hello, from what I understand, if you cannot download it from the website, our scraper won't be able to download it either
